experiment_name: 'bush-500'
experiment_description: 'Contains analysis of 500 Bush answers'

lexical:
  richness:
    mattr: true
    mtld: true
  word_length: true
  function_words: true
  density: true
  sentiment:
    model: 'j-hartmann/emotion-english-distilroberta-base'
    classes: 7
  legmonena:
    hapax: true
    dislegomena: true
    trilegomina: true
syntactic:
  pos_frequency: true
  clauses: true
  dependency_distance: true

# Data
data:
  data_path: 'data/100_bush_pairs.json'
  target_key: 'answer' # Could be something else like 'CAPT JACK SPARROW'
  output_path: 'output/bush/'