experiment_name: 'bush-1-full'
experiment_description: 'Contains analysis of ALL Bush answers'

lexical:
  richness:
    mattr: true
    mtld: true
  word_length: true
  function_words: true
  density: true
  sentiment: true
syntactic:
  pos_frequency: true
  clauses: true
  dependency_distance: true

# Data
data:
  data_path: 'data/O2_approved_pairs.json'
  output_path: 'output/bush/'